### ISSUE TITLE
Error when Double click on terminal side

### ISSUE THREAD

**Issue by sonbui00** [raphamorim/rio#316]
When I double-click on the terminal side, I get the error
I can fix it when I have time this week.
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/rio`
thread 'main' panicked at rio/src/crosswords/grid/mod.rs:554:31:
index out of bounds: the len is 189 but the index is 190
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:162:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/slice/index.rs:261:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/vec/mod.rs:2675:9
   6: <rio::crosswords::grid::row::Row<T> as core::ops::index::Index<rio::crosswords::pos::Column>>::index
             at ./Projects/os/rio/rio/src/crosswords/grid/row.rs:199:20
   7: <rio::crosswords::grid::Grid<T> as core::ops::index::Index<rio::crosswords::pos::Pos>>::index
             at ./Projects/os/rio/rio/src/crosswords/grid/mod.rs:418:23
   8: <rio::crosswords::grid::GridIterator<T> as core::iter::traits::iterator::Iterator>::next
             at ./Projects/os/rio/rio/src/crosswords/grid/mod.rs:554:31
   9: rio::crosswords::Crosswords<U>::semantic_search_right
             at ./Projects/os/rio/rio/src/crosswords/mod.rs:818:21
  10: rio::selection::Selection::range_semantic
             at ./Projects/os/rio/rio/src/selection.rs:338:19
  11: rio::selection::Selection::to_range
             at ./Projects/os/rio/rio/src/selection.rs:309:22
  12: rio::screen::Screen::start_selection
             at ./Projects/os/rio/rio/src/screen/mod.rs:928:34
  13: rio::screen::Screen::on_left_click
             at ./Projects/os/rio/rio/src/screen/mod.rs:1107:17
  14: rio::sequencer::Sequencer::run::{{closure}}::{{closure}}
             at ./Projects/os/rio/rio/src/sequencer.rs:452:41
  15: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/app_state.rs:87:13
  16: winit::platform_impl::platform::app_state::EventLoopHandler<T>::with_callback
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/app_state.rs:70:13
  17: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/app_state.rs:86:9
  18: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/app_state.rs:314:13
  19: winit::platform_impl::platform::app_state::AppState::cleared
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/app_state.rs:616:21
  20: winit::platform_impl::platform::observer::control_flow_end_handler::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/observer.rs:79:21
  21: winit::platform_impl::platform::observer::control_flow_handler::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/observer.rs:41:9
  22: std::panicking::try::do_call
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  23: ___rust_try
  24: std::panicking::try
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  25: std::panic::catch_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  26: winit::platform_impl::platform::event_loop::stop_app_on_panic
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/event_loop.rs:465:11
  27: winit::platform_impl::platform::observer::control_flow_handler
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/observer.rs:39:5
  28: winit::platform_impl::platform::observer::control_flow_end_handler
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/observer.rs:74:9
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <() as objc2::message::MessageArguments>::__invoke
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/message/mod.rs:531:39
  40: objc2::message::platform::send_unverified
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/message/apple/mod.rs:35:34
  41: objc2::message::MessageReceiver::send_message
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/message/mod.rs:233:53
  42: winit::platform_impl::platform::appkit::application::NSApplication::run
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/macros/__attribute_helpers.rs:126:21
  43: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/event_loop.rs:306:26
  44: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  45: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9
  46: std::panicking::try::do_call
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  47: ___rust_try
  48: std::panicking::try
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  49: std::panic::catch_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  50: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/event_loop.rs:295:32
  51: objc2::rc::autorelease::autoreleasepool
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/rc/autorelease.rs:438:15
  52: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/event_loop.rs:277:9
  53: <winit::event_loop::EventLoop<T> as winit::platform::run_on_demand::EventLoopExtRunOnDemand>::run_on_demand
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform/run_on_demand.rs:74:9
  54: rio::sequencer::Sequencer::run::{{closure}}
             at ./Projects/os/rio/rio/src/sequencer.rs:65:17
  55: rio::main::{{closure}}
             at ./Projects/os/rio/rio/src/main.rs:146:46
  56: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  57: tokio::runtime::coop::with_budget
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  58: tokio::runtime::coop::budget
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  59: tokio::runtime::park::CachedParkThread::block_on
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  60: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  61: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  62: tokio::runtime::context::runtime::enter_runtime
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  63: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  64: tokio::runtime::runtime::Runtime::block_on
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
  65: rio::main
             at ./Projects/os/rio/rio/src/main.rs:148:5
  66: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at /Users/sonbui/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/app_state.rs:377:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
   4: winit::platform_impl::platform::app_state::AppState::clear_callback
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/app_state.rs:377:9
   5: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/event_loop.rs:325:13
   6: objc2::rc::autorelease::autoreleasepool
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc2-0.4.1/src/rc/autorelease.rs:438:15
   7: winit::platform_impl::platform::event_loop::EventLoop<T>::run_on_demand
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform_impl/macos/event_loop.rs:277:9
   8: <winit::event_loop::EventLoop<T> as winit::platform::run_on_demand::EventLoopExtRunOnDemand>::run_on_demand
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.2/src/platform/run_on_demand.rs:74:9
   9: rio::sequencer::Sequencer::run::{{closure}}
             at ./Projects/os/rio/rio/src/sequencer.rs:65:17
  10: rio::main::{{closure}}
             at ./Projects/os/rio/rio/src/main.rs:146:46
  11: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  12: tokio::runtime::coop::with_budget
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  13: tokio::runtime::coop::budget
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  14: tokio::runtime::park::CachedParkThread::block_on
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  15: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  17: tokio::runtime::context::runtime::enter_runtime
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  18: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  19: tokio::runtime::runtime::Runtime::block_on
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
  20: rio::main
             at ./Projects/os/rio/rio/src/main.rs:148:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by raphamorim** [comment]
Hey @sonbui00 thanks for the issue,

How can I reproduce it? Double click where on terminal side?

**Comment by sonbui00** [comment]
@raphamorim On the right side (red)
<img width="737" alt="image" src="https://github.com/raphamorim/rio/assets/6426576/52ed9370-5506-4594-b596-781dc9c3179b">

**Comment by raphamorim** [comment]
Wow good finding, pushed the fix for it. Thank you for reporting, let me know anything
