### ISSUE TITLE
rio panicked at sugarloaf's "request adapter" line

### ISSUE THREAD

**Issue by bagasme** [raphamorim/rio#447]
Hi,

I'm building current main (commit 7fc263754d) with debugging info enabled (just plain `cargo build`) on my Arch Linux machine.
When I run rio, I got backtrace (run with `RUST_BACKTRACE=full target/debug/rio`):

```
MESA-INTEL: warning: Haswell Vulkan support is incomplete
thread 'main' panicked at /home/bagas/repo/rio/sugarloaf/src/context/mod.rs:99:14:
Request adapter
stack backtrace:
   0:     0x555ac4d8af1c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x555ac4d8af1c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555ac4d8af1c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x555ac4d8af1c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x555ac4dba3ac - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x555ac4dba3ac - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x555ac4d8680e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x555ac4d8ad04 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x555ac4d8ad04 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x555ac4d8c793 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x555ac4d8c4ac - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
<snipped>...
```

rio process exited with SIGABRT on release build (`cargo build --release`).

Debugging artifacts:

* [full `RUST_BACKTRACE=full` output](https://github.com/raphamorim/rio/files/14156075/rust_backtrace.txt)
* [gdb session with backtrace](https://github.com/raphamorim/rio/files/14156076/gdb.txt)
* [release build core dump](https://github.com/raphamorim/rio/files/14156079/dump.gz)

**Comment by bagasme** [comment]
> Hey there @bagasme thanks for the issue!
> 
> Hmm, very interesting. I never saw this error, did a little bit of research and looks it's common:
> 
>     * https://www.reddit.com/r/wine_gaming/comments/ktww3h/i_keep_getting_the_warning_haswell_vulkan_support/
> 
>     * https://www.reddit.com/r/vulkan/comments/dfwy1h/vulkan_on_haswell_gpu/
> 
>     * https://www.reddit.com/r/vulkan/comments/xjftzl/mesaintel_warning_haswell_vulkan_support_is/
> 
>     * https://forum.manjaro.org/t/mesa-intel-haswell-support-is-incomplete/132937
> 
>     * https://forums.gentoo.org/viewtopic-p-8781470.html?sid=87d9983f958d80f59a0322b4b75cb02f
> 
>     * [WARNING: Haswell Vulkan support is incomplete - Error: No DRI3 support SaschaWillems/Vulkan#226](https://github.com/SaschaWillems/Vulkan/issues/226)
> 
> 
> which rio version are you using?
> 
> also, might be that you need to enable DRI3. On arch should be something like
> 
> Install the driver
> 
> ```shell
> pacman -S vulkan-devel vulkan-intel
> ```
> 
> Install the project's dependencies
> 
> ```shell
> pacman -S assimp libxcb
> ```
> 
> then enable the DRI
> 
> ```shell
> cat << EOF > /etc/X11/xorg.conf.d/20-intel.conf
> Section "Device"
>    Identifier  "Intel Graphics"
>    Driver      "intel"
>    Option      "DRI"    "3"
> EndSection
> EOF
> ```

I can still reproduce the backtrace, unfortunately.

**Comment by gustavoteixeirah** [comment]
Hello!
After installing it with `sudo pacman -S rio`, I have this issue on Arch linux:

```bash
$ rio
thread 'main' panicked at /usr/src/debug/rio/rio-0.0.35/sugarloaf/src/context/mod.rs:60:14:
Request adapter
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    48374 IOT instruction (core dumped)  rio
Command failed
```

Running with backtrace=full because with =1 didn't show anything new

```bash
$ RUST_BACKTRACE=full rio
thread 'main' panicked at /usr/src/debug/rio/rio-0.0.35/sugarloaf/src/context/mod.rs:60:14:
Request adapter
stack backtrace:
   0:     0x5794d08b532c - <unknown>
   1:     0x5794d05318a0 - <unknown>
   2:     0x5794d08b0b2d - <unknown>
   3:     0x5794d08b50c5 - <unknown>
   4:     0x5794d08b6833 - <unknown>
   5:     0x5794d08b657a - <unknown>
   6:     0x5794d08b6e69 - <unknown>
   7:     0x5794d08b6c32 - <unknown>
   8:     0x5794d08b5806 - <unknown>
   9:     0x5794d08b69c0 - <unknown>
  10:     0x5794d0458795 - <unknown>
  11:     0x5794d0458753 - <unknown>
  12:     0x5794d07b7fb5 - <unknown>
  13:     0x5794d07c8e84 - <unknown>
  14:     0x5794d07d3304 - <unknown>
  15:     0x5794d07d2106 - <unknown>
  16:     0x5794d071c1f3 - <unknown>
  17:     0x5794d071c3df - <unknown>
  18:     0x5794d08a85b5 - <unknown>
  19:     0x5794d07d6cac - <unknown>
  20:     0x7951c8c7acd0 - <unknown>
  21:     0x7951c8c7ad8a - __libc_start_main
  22:     0x5794d04a2a55 - <unknown>
  23:                0x0 - <unknown>
[1]    48713 IOT instruction (core dumped)  RUST_BACKTRACE=full rio
Command failed
```

**Comment by raphamorim** [comment]
@gustavoteixeirah is your driver also intel?

@bagasme did you install [xf86-video-intel](https://archlinux.org/packages/?name=xf86-video-intel) ?

**Comment by Joao620** [comment]
Contributing for the topic, I've encountered the same issue, but on voidlinux, on a intel laptop. I've installed a lot of packages (also the xf86-video-intel), but the one that resolved was `mesa-vulkan-intel`. 

Just for completion,  here all the packages that i installed
* vulkan-intel
* intel-video-accel
* xf86-video-intel
* linux-firmware-intel
