### ISSUE TITLE
Crash on startup in ubuntu 24.04

### ISSUE THREAD

**Issue by thiagomg** [raphamorim/rio#559]
I am experiencing a crash when starting rio in ubuntu 24.04. It happens every time I start the application before anything is shown.

---

```bash
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
uname -a
Linux linlap-0124 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

```gdb
gdb ./rio
GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./rio...
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/thiago/src/3rd/rio/target/debug/rio.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) run
Starting program: /home/thiago/src/3rd/rio/target/debug/rio

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n])
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlidec.so.1
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlicommon.so.1
[New Thread 0x7ffff78006c0 (LWP 284861)]
[New Thread 0x7ffff74006c0 (LWP 284862)]
[New Thread 0x7ffff70006c0 (LWP 284863)]
[New Thread 0x7ffff6c006c0 (LWP 284864)]
[New Thread 0x7ffff68006c0 (LWP 284865)]
[New Thread 0x7ffff64006c0 (LWP 284866)]
[New Thread 0x7ffff60006c0 (LWP 284867)]
[New Thread 0x7ffff5c006c0 (LWP 284868)]
[New Thread 0x7ffff58006c0 (LWP 284869)]
[New Thread 0x7ffff54006c0 (LWP 284870)]
[New Thread 0x7ffff50006c0 (LWP 284871)]
[New Thread 0x7ffff4c006c0 (LWP 284872)]
[New Thread 0x7ffff48006c0 (LWP 284873)]
[New Thread 0x7ffff44006c0 (LWP 284874)]
[New Thread 0x7fffefe006c0 (LWP 284875)]
[New Thread 0x7fffefa006c0 (LWP 284876)]
[New Thread 0x7fffef6006c0 (LWP 284877)]
[New Thread 0x7fffef2006c0 (LWP 284878)]
[New Thread 0x7fffeee006c0 (LWP 284879)]
[New Thread 0x7fffeea006c0 (LWP 284880)]
[New Thread 0x7fffee6006c0 (LWP 284882)]
[Detaching after vfork from child process 284883]
[Detaching after vfork from child process 284885]
[Detaching after vfork from child process 284889]
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/libvulkan_virtio.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libtinfo.so.6
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/libvulkan_intel_hasvk.so
warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/libvulkan_intel.so
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libVkLayer_MESA_device_select.so
warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libcap.so.2
[New Thread 0x7fffd50006c0 (LWP 284894)]
[New Thread 0x7fffbd2006c0 (LWP 284895)]
[New Thread 0x7fffb1c006c0 (LWP 284896)]
[New Thread 0x7fffb12006c0 (LWP 284897)]
[New Thread 0x7fffa7e006c0 (LWP 284898)]
[New Thread 0x7fffa74006c0 (LWP 284899)]
[New Thread 0x7fffa6a006c0 (LWP 284900)]
[New Thread 0x7fffa60006c0 (LWP 284901)]
[New Thread 0x7fffa56006c0 (LWP 284902)]
[Thread 0x7fffb12006c0 (LWP 284897) exited]
[Thread 0x7fffb1c006c0 (LWP 284896) exited]
[Thread 0x7fffbd2006c0 (LWP 284895) exited]
[Thread 0x7fffd50006c0 (LWP 284894) exited]
[New Thread 0x7fffd50006c0 (LWP 284903)]
[New Thread 0x7fffbd2006c0 (LWP 284904)]
[New Thread 0x7fffb1c006c0 (LWP 284905)]
[New Thread 0x7fffb12006c0 (LWP 284908)]

Thread 1 "rio" received signal SIGSEGV, Segmentation fault.
_dl_close (_map=0x0) at ./elf/dl-close.c:770
warning: 770	./elf/dl-close.c: No such file or directory
(gdb) bt
#0  _dl_close (_map=0x0) at ./elf/dl-close.c:770
#1  0x00007ffff7fc651c in __GI__dl_catch_exception (exception=exception@entry=0x7ffffffa5e40, operate=0x7ffff7fc7750 <_dl_close>, args=0x0)
    at ./elf/dl-catch.c:237
#2  0x00007ffff7fc6669 in _dl_catch_error (objname=0x7ffffffa5ea8, errstring=0x7ffffffa5eb0, mallocedp=0x7ffffffa5ea7, operate=<optimized out>,
    args=<optimized out>) at ./elf/dl-catch.c:256
#3  0x00007ffff7a97c73 in _dlerror_run (operate=<optimized out>, args=<optimized out>) at ./dlfcn/dlerror.c:138
#4  0x00007ffff7a979a6 in __dlclose (handle=<optimized out>) at ./dlfcn/dlclose.c:31
#5  0x00007fffd4201e0d in ProducerCleanup () from /lib/x86_64-linux-gnu/libnvidia-vulkan-producer.so
#6  0x00007fffd42020db in ProducerInit () from /lib/x86_64-linux-gnu/libnvidia-vulkan-producer.so
#7  0x00007fffd6a1a0e2 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.535.171.04
#8  0x00007fffd6a4442f in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.535.171.04
#9  0x00007fffd6a6844d in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.535.171.04
#10 0x00007ffff5d75b50 in ?? () from /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
#11 0x00007ffff69bc0da in ?? () from /lib/x86_64-linux-gnu/libvulkan.so.1
#12 0x000055555713091f in ash::extensions::khr::swapchain::Swapchain::create_swapchain (self=0x7ffffffa6528, create_info=0x7ffffffa6730,
    allocation_callbacks=...) at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ash-0.37.3+1.3.251/src/extensions/khr/swapchain.rs:54
#13 0x000055555705eb04 in wgpu_hal::vulkan::Device::create_swapchain (self=0x555558d0d260, surface=0x555558634810, config=0x7ffffffa8030,
    provided_old_swapchain=...) at src/vulkan/device.rs:607
#14 0x0000555557070866 in wgpu_hal::vulkan::instance::{impl#6}::configure (self=0x555558634810, device=0x555558d0d260, config=0x7ffffffa8030)
    at src/vulkan/instance.rs:979
#15 0x0000555556d626de in wgpu_core::global::Global::surface_configure<wgpu_hal::vulkan::Api> (self=0x555558c630a0, surface_id=..., device_id=...,
    config=0x7ffffffa96a0) at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.21.0/src/device/global.rs:2060
#16 0x0000555556b39899 in wgpu::backend::wgpu_core::{impl#7}::surface_configure (self=0x555558c630a0, surface=0x7ffffffa8950, surface_data=0x555558cb9280,
    device=0x7ffffffa8958, _device_data=0x555558d10520, config=0x7ffffffa96a0) at src/backend/wgpu_core.rs:749
#17 0x0000555556b54bfa in wgpu::context::{impl#5}::surface_configure<wgpu::backend::wgpu_core::ContextWgpuCore> (self=0x555558c630a0, surface=0x7ffffffef768,
    surface_data=..., device=0x7ffffffa91a0, device_data=..., config=0x7ffffffa96a0) at src/context.rs:2128
#18 0x0000555556bce750 in wgpu::Surface::configure (self=0x7ffffffef738, device=0x7ffffffa9180, config=0x7ffffffa96a0) at src/lib.rs:5096
#19 0x0000555555911178 in sugarloaf::context::{impl#0}::new::{async_fn#0} () at sugarloaf/src/context/mod.rs:151
#20 0x0000555555957618 in sugarloaf::sugarloaf::{impl#7}::new::{async_fn#0} () at sugarloaf/src/sugarloaf.rs:120
#21 0x00005555558ce673 in rio::screen::{impl#0}::new::{async_fn#0} () at frontends/rioterm/src/screen/mod.rs:159
#22 0x000055555580119c in rio::router::{impl#3}::new::{async_fn#0} () at frontends/rioterm/src/router/mod.rs:365
#23 0x00005555558aaba7 in rio::sequencer::{impl#0}::run::{async_fn#0} () at frontends/rioterm/src/sequencer.rs:63
#24 0x000055555593f3e0 in rio::main::{async_block#0} () at frontends/rioterm/src/main.rs:149
#25 0x000055555585aee3 in tokio::runtime::park::{impl#4}::block_on::{closure#0}<rio::main::{async_block_env#0}> ()
    at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/park.rs:281
#26 0x000055555585acf4 in tokio::runtime::coop::with_budget<core::task::poll::Poll<core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>>, tokio::runtime::park::{impl#4}::block_on::{closure_env#0}<rio::main::{async_block_env#0}>> (budget=..., f=...)
    at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107
#27 tokio::runtime::coop::budget<core::task::poll::Poll<core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>>, tokio::runtime::park::{impl#4}::block_on::{closure_env#0}<rio::main::{async_block_env#0}>> (f=...)
    at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73
#28 tokio::runtime::park::CachedParkThread::block_on<rio::main::{async_block_env#0}> (self=0x7ffffffefbff, f=...)
    at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/park.rs:281
#29 0x000055555583b0c3 in tokio::runtime::context::blocking::BlockingRegionGuard::block_on<rio::main::{async_block_env#0}> (self=0x7fffffff3290, f=...)
    at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/blocking.rs:66
#30 0x000055555583aeba in tokio::runtime::scheduler::multi_thread::{impl#0}::block_on::{closure#0}<rio::main::{async_block_env#0}> (blocking=0x7fffffff3290)
    at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/mod.rs:87
#31 0x0000555555863ac6 in tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::{impl#0}::block_on::{closure_env#0}<rio::main::{async_block_env#0}>, core::result::Result<(), alloc::boxed::Box<dyn core::error::Error, alloc::alloc::Global>>> (handle=0x7fffffffba48,
    allow_block_in_place=true, f=...) at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65
#32 0x000055555583ae4b in tokio::runtime::scheduler::multi_thread::MultiThread::block_on<rio::main::{async_block_env#0}> (self=0x7fffffffba20,
    handle=0x7fffffffba48, future=...)
    at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/mod.rs:86
#33 0x0000555555931928 in tokio::runtime::runtime::Runtime::block_on<rio::main::{async_block_env#0}> (self=0x7fffffffba18, future=...)
    at /home/thiago/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/runtime.rs:351
#34 0x0000555555885f5c in rio::main () at frontends/rioterm/src/main.rs:155
(gdb) q
A debugging session is active.

	Inferior 1 [process 284849] will be killed.

Quit anyway? (y or n) y
```

**Comment by raphamorim** [comment]
Hey @thiagomg thanks for the issue!

Very interesting that is crashing on Vulkan/wgpu level. Which Rio version are you using?

**Comment by rcspam** [comment]
same here with ubuntu 24.04 and 
```
$ rio --version
rioterm 0.2.13

$ rio
wp_linux_drm_syncobj_manager_v1#73: error 0: surface already exists
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@73: 
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@73: 

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-25.0.0/src/backend/wgpu_core.rs:3561:18:
wgpu error: Validation Error

Caused by:
  In Surface::configure
    Surface does not support the adapter's queue family


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Erreur de segmentation

```

**Comment by rcspam** [comment]
same issue withrioterm 0.2.14

**Comment by raphamorim** [comment]
Both backtraces point at the old wgpu surface path, which was replaced by the native Vulkan renderer in 2026. Closing; please retest on 0.4.12 and file fresh if it still crashes.
