### ISSUE TITLE
Trying to build sugarloaf

### ISSUE THREAD

**Issue by melroy89** [raphamorim/rio#744]
Hi,

Me again. I'm trying to help you with anti-alias. Or well trying to disabling it. I notice the rio-backend uses the Sugarloaf.

And I think the Sugarloaf is doing the heavy rendering lifting within Rio terminal for the GPU. Right?

So I try to run the example, as stated in the [README](https://github.com/raphamorim/rio/tree/main/sugarloaf). I `cd`-ed into the sugarloaf sub-directory, and ran:

```sh
$ cargo run --example text
```

Well that gives me:

```bash
Some errors have detailed explanations: E0282, E0369, E0432.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `rio-window` (lib) due to 7 previous errors
```

That is too bad, full output:

---

```bash
error: The platform you're compiling for is not supported by winit
  --> rio-window/src/platform_impl/mod.rs:66:1
   |
66 | compile_error!("The platform you're compiling for is not supported by winit");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling glslang v0.6.1
error[E0432]: unresolved import `self::platform`
  --> rio-window/src/platform_impl/mod.rs:22:15
   |
22 | pub use self::platform::*;
   |               ^^^^^^^^ could not find `platform` in `self`

error[E0432]: unresolved imports `crate::platform_impl::PlatformCustomCursor`, `crate::platform_impl::PlatformCustomCursorSource`
 --> rio-window/src/cursor.rs:8:28
  |
8 | use crate::platform_impl::{PlatformCustomCursor, PlatformCustomCursorSource};
  |                            ^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PlatformCustomCursorSource` in `platform_impl`
  |                            |
  |                            no `PlatformCustomCursor` in `platform_impl`

error[E0432]: unresolved import `crate::platform_impl::PlatformIcon`
 --> rio-window/src/icon.rs:1:5
  |
1 | use crate::platform_impl::PlatformIcon;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PlatformIcon` in `platform_impl`

error[E0432]: unresolved import `crate::platform_impl::PlatformSpecificWindowAttributes`
 --> rio-window/src/window.rs:7:34
  |
7 | use crate::platform_impl::{self, PlatformSpecificWindowAttributes};
  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `PlatformSpecificWindowAttributes` in `platform_impl`

   Compiling spirv-cross2 v0.4.6
error[E0282]: type annotations needed
  --> rio-window/src/event_loop.rs:77:9
   |
77 |         EventLoop::builder()
   |         ^^^^^^^^^ cannot infer type for type parameter `T` declared on the struct `EventLoop`

error[E0369]: binary operation `==` cannot be applied to type `&std::option::Option<MonitorHandle>`
    --> rio-window/src/window.rs:1772:16
     |
1767 | #[derive(Clone, Debug, PartialEq, Eq)]
     |                        --------- in this derive macro expansion
...
1772 |     Borderless(Option<MonitorHandle>),
     |                ^^^^^^^^^^^^^^^^^^^^^
     |
     = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I also notice the Makefile. So lets try that. Well luckily for me `make install` exactly succeeded.

But `make run`,  which seems to trigger the build, gives also errors:

```bash
$ make run
cargo build -p sugarloaf-wasm --target wasm32-unknown-unknown
  Downloaded wasm-bindgen-futures v0.4.45
  Downloaded wasm-bindgen-macro v0.2.95
  Downloaded wasm-bindgen-backend v0.2.95
  Downloaded wasm-bindgen v0.2.95
  Downloaded wasm-bindgen-test-macro v0.3.45
  Downloaded web-time v1.1.0
  Downloaded pin-project v1.1.6
  Downloaded console_log v0.2.2
  Downloaded wasm-bindgen-test v0.3.45
  Downloaded pin-project-internal v1.1.6
  Downloaded js-sys v0.3.72
  Downloaded gethostname v0.4.3
  Downloaded bumpalo v3.16.0
  Downloaded wasm-bindgen-macro-support v0.2.95
  Downloaded console_error_panic_hook v0.1.7
  Downloaded web-sys v0.3.72
  Downloaded 16 crates (1.6 MB) in 0.80s
error: package ID specification `sugarloaf-wasm` did not match any packages
make: *** [Makefile:17: build] Error 101
```

Now I'm out of ideas how to get started.

What I would want:

- Getting started with Sugerloaf
- Running as a native app. I don't really need or want wasm in order to contribute to Rio.
- `make run` or `cargo run` should give me an example window for example, to show off Sugarloaf?
- Running on GNU/Linux

**Comment by melroy89** [comment]
I manage to get it almost working... 

I changed the `Cargo.toml` of Sugarloaf to explicitly set to use x11, I bet there is a better way tho:

```toml
[dev-dependencies]
rio-window = { workspace = true, default-features = false, features = ["x11"] }
```

The text example still crashes too bad:

```bash
     Running `/media/melroy/Data/Projects/rio/target/debug/examples/text`
thread 'main' panicked at sugarloaf/src/layout/content.rs:443:40:
index out of bounds: the len is 0 but the index is 18446744073709551615
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_bounds_check
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/panicking.rs:276:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:308:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/slice/index.rs:27:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/alloc/src/vec/mod.rs:2932:9
   6: sugarloaf::layout::content::Content::add_text_with_id
             at ./src/layout/content.rs:443:40
   7: sugarloaf::layout::content::Content::add_text
             at ./src/layout/content.rs:407:20
   8: <text::Application as rio_window::application::ApplicationHandler>::window_event
             at ./examples/text.rs:121:17
   9: rio_window::event_loop::dispatch_event_for_app
             at /media/melroy/Data/Projects/rio/rio-window/src/event_loop.rs:687:13
  10: rio_window::event_loop::EventLoop<T>::run_app::{{closure}}
             at /media/melroy/Data/Projects/rio/rio-window/src/event_loop.rs:273:38
  11: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:294:13
  12: rio_window::platform_impl::platform::x11::EventLoop<T>::single_iteration
             at /media/melroy/Data/Projects/rio/rio-window/src/platform_impl/linux/x11/mod.rs:608:17
  13: rio_window::platform_impl::platform::x11::EventLoop<T>::pump_events
             at /media/melroy/Data/Projects/rio/rio-window/src/platform_impl/linux/x11/mod.rs:444:13
  14: rio_window::platform_impl::platform::x11::EventLoop<T>::run_on_demand
             at /media/melroy/Data/Projects/rio/rio-window/src/platform_impl/linux/x11/mod.rs:405:19
  15: rio_window::platform_impl::platform::EventLoop<T>::run_on_demand
             at /media/melroy/Data/Projects/rio/rio-window/src/platform_impl/linux/mod.rs:821:56
  16: rio_window::platform_impl::platform::EventLoop<T>::run
             at /media/melroy/Data/Projects/rio/rio-window/src/platform_impl/linux/mod.rs:814:9
  17: rio_window::event_loop::EventLoop<T>::run_app
             at /media/melroy/Data/Projects/rio/rio-window/src/event_loop.rs:272:9
  18: text::Application::run
             at ./examples/text.rs:43:22
  19: text::main
             at ./examples/text.rs:20:13
  20: core::ops::function::FnOnce::call_once
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14/library/core/src/ops/function.rs:250:5
```

**Comment by raphamorim** [comment]
Hey @melroy89 thanks for the issue!

Dang, good catch i forgot sugarloaf was using winit/rio-window under the hood for examples...

1. Regarding the crash, push the fix for main 👍 
2. Regarding `But make run, which seems to trigger the build, gives also errors:` pushed a fix for that too, make run should just run the terminal only

**Comment by melroy89** [comment]
> Hey @melroy89 thanks for the issue!
> 
> Dang, good catch i forgot sugarloaf was using winit/rio-window under the hood for examples...
> 
>     1. Regarding the crash, push the fix for main 👍
> 
>     2. Regarding `But make run, which seems to trigger the build, gives also errors:` pushed a fix for that too, make run should just run the terminal only

great, let me try to test it right away!

**Comment by melroy89** [comment]
Thank you! it works now!!

![image](https://github.com/user-attachments/assets/31aa86e7-31c9-4864-8462-0cdcb86a4ad0)

**Comment by melroy89** [comment]
`make run` still fails tho:

```
error: package ID specification `sugarloaf-wasm` did not match any packages
make: *** [Makefile:17: build] Error 101
```

**Comment by raphamorim** [comment]
ah is true, I forgot to update this command on makefile..
thank you, just pushed an update

**Comment by melroy89** [comment]
Ps. You also might want to add [`env_logger`](https://docs.rs/env_logger/latest/env_logger/) to the cargo file of Sugarloaf?

Add somewhere add `env_logger::init();` (maybe only in dev mode).

Since that allows me to actually give some output with `RUST_LOG=info`:

![image](https://github.com/user-attachments/assets/86d717e9-2841-4962-9289-8e10fa046e94)

And that gives the option to add `info!("..");` for example, or warnings or errors. Which might be easier for the future in case of debugging issues at the user-side. Just saying.

Apparently wgpu_hal is also using the `log`. But `env_logger` is one of the many ways to get the log output, in this case to the console log...

**Comment by melroy89** [comment]
ow I see you are using tracing...

**Comment by raphamorim** [comment]
It's a good question, i often see sugarloaf as direct dependency of Rio, so whenever I do a debug I run with RIO_LOG_LEVEL, but for people that use sugarloaf solely it's needed.

@melroy89 feel free to join the discord as well, is valuable to bring more discussions there https://discord.gg/zRvJjmKGwS
